#!/bin/bash

#set -x
set -e

export DEBEMAIL="hendrik@askra.de"
export DEBFULLNAME="Hendrik Tews"

timestamp=$(date '+%Y-%m-%d')

dir="prooftree-$timestamp"
webdir=/home/tews/www/alfa-www/askra-root/software/prooftree

export CVSROOT=$(cat CVS/Root)
echo using CVSROOT $CVSROOT


#######################################################################
# make source and bin package

version=$(cat version.txt)
#version=0.11

subdir="prooftree-$version"

tgzfile="$subdir.tar.gz"

pushd /tmp/tews

rm -rf prooftree-*

mkdir $dir
pushd $dir

cvs export -r HEAD -d $subdir src/proof-tree
#cvs export -r prooftree-release-0-11 -d $subdir src/proof-tree

pushd $subdir

rm -f make-release make-deb-package

popd
# back in $dir

mv $subdir/debian .

tar -czf $tgzfile $subdir

cp $tgzfile prooftree_$version.orig.tar.gz

cp -a $subdir $subdir-orig

mv debian $subdir

pushd $subdir

#./configure --prefix /usr

exit 0

debuild -i -us -uc

popd
# back in $dir

debfile=$(ls *.deb)

echo
echo copy $debfile to $webdir
echo -n [Y/n]?
read answer

if [  ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

cp $debfile $webdir/releases
