#!/bin/bash

#set -x
set -e

timestamp=$(date '+%Y-%m-%d')

dir="prooftree-bundle-$timestamp"

coqversion=8.3pl2
coqdir=/home/tews/src/qsrc
coqorig=orig-$coqversion
coqpatch=patch-$coqversion

if [ $(hostname) = "blau" ] ; then
    storecvs=/home/tews/Store
else
    storecvs=blau:/home/tews/Store
fi

webdir=/home/tews/www/alfa-www/askra-root/software/prooftree

sed -i.$(date +%s)~ -e "s/^<DT>XXXX-XX-XX/<DT>$timestamp/" changes.html

cvsmessage="* prepare changes.html for release"

cat - ChangeLog > newchangelog <<EOF
$(date +%Y-%m-%d)  Hendrik Tews <prooftree@askra.de>

	$cvsmessage

EOF

mv newchangelog ChangeLog

cvs update | grep -v '^?' | grep -v '^cvs update: Updating'

echo
echo Commit and copy patched [recent-]changes.html : 
echo cvs commit -m "$cvsmessage" . ?
echo -n [Y/n]?
read answer

if [  ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

cvs commit -m "$cvsmessage" .
cp changes.html $webdir

sed -n -e '/RECENT CHANGES START/,/RECENT CHANGES END/p' \
    < changes.html > $webdir/recent-changes.html

pushd /tmp/tews

rm -rf prooftree-bundle-*

mkdir $dir
pushd $dir

cvs -d :pserver:tews@cvs.inf.ed.ac.uk:/disk/cvs/proofgen \
    export -r ProofTreeBranch -d ProofGeneral_ProofTreeBranch ProofGeneral

cvs -d $storecvs export -r HEAD -d prooftree src/proof-tree

pushd prooftree

rm -f make-bundle

popd
# back in $dir


coq_patch_dir=coq-patch-$coqversion
mkdir $coq_patch_dir
(cd $coqdir; diff -ru $coqorig $coqpatch) \
    | grep -v '^Only in' \
    | sed -e "s/^+++ $coqpatch/+++ coq-$coqversion/" \
    > $coq_patch_dir/coq-id-patch


mv prooftree/README-bundle README
mv prooftree/README-coq-id-patch $coq_patch_dir/README


popd
# back in /tmp/tews

tgzfile="$dir.tar.gz"

tar -czf $tgzfile $dir


echo
echo copy README-bundle $tgzfile
echo to $webdir
echo -n [Y/n]?
read answer

if [  ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

cp $dir/README $webdir/README-bundle
cp $tgzfile $webdir/releases


popd
# back to startdir


echo
echo Fix download links in website ?
echo -n [Y/n]?
read answer

if [  ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

oldlink=$(sed -n -e '/LATEST VERSION LINK/ {s/<![^>]*>//
       	  	   	   	            s/\[prooftree-bundle-//
				            s/.tar.gz\]//
                                            s/>$/>,/
                                            p
				           }' < $webdir/index.shtml)


newlink="<!-- LATEST VERSION LINK --><A HREF=\"releases/$tgzfile\">[$tgzfile]<\\/A>"

cp $webdir/index.shtml $webdir/index.shtml.$(date +%s)~

sed -e "/LATEST VERSION LINK/ c$newlink" \
    -e "/^<P>Previous versions:/ {p
                             c$oldlink
                            }" \
    < $webdir/index.shtml > $webdir/indexnew.shtml

mv $webdir/indexnew.shtml $webdir/index.shtml


echo
echo Upload website?
echo -n [Y/n]?
read answer

if [  ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

/home/tews/www/update-sys

release_tag=prooftree-release-$timestamp

echo
echo cvs tag $release_tag ?
echo -n [Y/n]?
read answer

if [ ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

cvs tag $release_tag

echo
echo bump version number?
echo -n [Y/n]?
read answer

if [  ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

pt_old_version=$(sed -e 's/0\.//' < version.txt)
pt_version=$(($pt_old_version + 1))


cp version.txt version.txt.$(date +%s)~
echo 0.$pt_version > version.txt

releasetime=$(TZ=UTC date '+%Y-%m-%d %H:%M:%S %Z')
cvsmessage="* release version 0.$pt_old_version on $releasetime"

cat - ChangeLog > newchangelog <<EOF
$(date +%Y-%m-%d)  Hendrik Tews <prooftree@askra.de>

	$cvsmessage

EOF

mv newchangelog ChangeLog

cvs update | grep -v '^?' | grep -v '^cvs update: Updating'


echo
echo cvs commit -m "$cvsmessage" . ??
echo -n [Y/n]?
read answer

if [  ${answer:=y} = n -o $answer = N ] ; then
    exit 0
fi

cvs commit -m "$cvsmessage" .

