
SOURCES:=\
	version.ml \
	util.ml \
	configuration.ml \
	gtk_ext.ml \
	draw_tree.ml \
	proof_window.ml \
	proof_tree.ml \
	input.ml \
	main.ml

TOCLEAN+=prooftree
prooftree: prooftree.opt

.PHONY: prooftree.opt
prooftree.opt: $(SOURCES)
	ocamlopt.opt -inline 0 -g -I +lablgtk2 -o prooftree \
		unix.cmxa lablgtk.cmxa \
		gtkInit.cmx $(SOURCES)

.PHONY: prooftree.byte
prooftree.byte: $(SOURCES)
	ocamlc.opt -g -I +lablgtk2 -o prooftree \
		unix.cma lablgtk.cma \
		gtkInit.cmo $(SOURCES)

version.ml: version.txt
	echo '(* This file is automatically generated from version. *)' > $@
	echo '(* DO NOT EDIT! *)' >> $@
	echo -n 'let version = "' >> $@
	cat version.txt >> $@
	echo '"' >> $@

clean:
	rm -f $(TOCLEAN)
	rm -f *.cmi *.cmo *.cmx *.o *.cma *.cmxa *.a

TAGS: $(SOURCES)
	otags $(SOURCES)
